export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Xeon s232 Inverter',
      category: 'Inverters',
      image: '/images/inverters.png',
      price: 6000,
      brand: 'Xeon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Xeon s232 Inverter',
      category: 'Inverters',
      image: '/images/inverter2.png',
      price: 8000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 10,
    },
    {
      _id: '3',
      name: 'Triple Power LFP',
      category: 'Inverters',
      image: '/images/TriplePowerLFPwebproduct.png',
      price: 10000,
      brand: 'SolarX',
      rating: 5,
      numReviews: 10,
      countInStock: 8,
    },
    {
      _id: '4',
      name: 'X3 Mega G2 1',
      category: 'Inverters',
      image: '/images/X3-mega-G2-1.png',
      price: 12000,
      brand: 'SolarX',
      rating: 3.5,
      numReviews: 10,
      countInStock: 7,
    },
    {
      _id: '5',
      name: 'Mini G4 front',
      category: 'Inverters',
      image: '/images/Mini-G4-front.png',
      price: 14000,
      brand: 'SolarX',
      rating: 3,
      description:'DC Input: 200% oversizing, 16A current, 40~450V wider MPPT voltage range In-built global MPP scan for higher yields',
      numReviews: 10,
      countInStock: 3,
    },
    {
      _id: '6',
      name: 'X3 hybrid G4 16',
      category: 'Inverters',
      image: '/images/X3-hybrid-G4.16.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: '7',
      name: 'J1 HES',
      category: 'Inverters',
      image: '/images/J1HES.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: '8',
      name: '1-BAT-front',
      category: 'Inverters',
      image: '/images/1-BAT-front.png',
      price: 16000,
      brand: 'SolarX',
      rating: 4,
      numReviews: 10,
      countInStock: 4,
    },
  ],
}
